
services:
    # PHP Service container 
    wiifarm_app1:
        build:
            args:
                user: wiifarm_user1
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: wiifarm_app1_image
        container_name: wiifarm_app1
        restart: unless-stopped
        depends_on:
            -   wiifarm_app1_mysql
        env_file:
           - ./core/.env
        working_dir: /var/www
        volumes:
            -   ./:/var/www
        networks:
            - wiifarm_app1_network
    #nginx service
    wiifarm1_webserver:
        image: nginx:alpine
        container_name: wiifarm1_webserver_container
        restart: unless-stopped
        ports:
            - "6162:80"
        depends_on:
            -  wiifarm_app1
        volumes:
            -   ./:/var/www
            - ./docker-compose/nginx/:/etc/nginx/conf.d
       
        networks:
            - wiifarm_app1_network
    #mysql service
    wiifarm_app1_mysql:
        image: mariadb:10.11
        container_name: wiifarm_app1_mysql_container
        restart: unless-stopped
        ports:
            - "3337:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wiifarm1_db
            MYSQL_USER: wiifarm_user
            MYSQL_PASSWORD: password
        volumes:
            -   wiifarm1_mysql_data:/var/lib/mysql
        
        networks:
            - wiifarm_app1_network
    wiifarm1_phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: wiifarm1_phpmyadmin_container
        restart: unless-stopped
        ports:
            -   "8383:80"
        environment:
            PMA_HOST: wiifarm_app1_mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 100M 
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            -   wiifarm_app1_mysql
        networks:
            - wiifarm_app1_network
    wiifarm1_redis:
        image: redis:7.2-alpine
        container_name: wiifarm1_redis_container
        ports:
            -  "7379:6379"
        networks:
            - wiifarm_app1_network
    
volumes:
    wiifarm1_mysql_data:
        driver: local
    
networks:
    wiifarm_app1_network:
        driver: bridge
