@extends($activeTemplate . 'layouts.master')

@section('content')
@php
    $unusedCount = $pins->getCollection()->where('status', 0)->count();
    $usedCount   = $pins->getCollection()->where('status', 1)->count();
@endphp

<div class="epin-page">

    {{-- ── Stats Strip ── --}}
    <div class="epin-stats">
        <div class="epin-stat">
            <div class="epin-stat-icon green"><i class="las la-qrcode"></i></div>
            <div>
                <p class="epin-stat-label">Total Pins</p>
                <p class="epin-stat-value">{{ $Totalpins }}</p>
                <p class="epin-stat-sub">Generated by you</p>
            </div>
        </div>
        <div class="epin-stat">
            <div class="epin-stat-icon amber"><i class="las la-dot-circle"></i></div>
            <div>
                <p class="epin-stat-label">Unused</p>
                <p class="epin-stat-value">{{ $pins->getCollection()->where('status', 0)->count() }}</p>
                <p class="epin-stat-sub">Ready to use</p>
            </div>
        </div>
        <div class="epin-stat">
            <div class="epin-stat-icon slate"><i class="las la-check-circle"></i></div>
            <div>
                <p class="epin-stat-label">Used</p>
                <p class="epin-stat-value">{{ $pins->getCollection()->where('status', 1)->count() }}</p>
                <p class="epin-stat-sub">Redeemed</p>
            </div>
        </div>

    </div>

    {{-- ── Action Cards ── --}}
    <div class="epin-actions">

        {{-- Generate Pin --}}
        <div class="epin-action-card">
            <div class="epin-action-header">
                <div class="epin-action-header-icon green"><i class="las la-plus-circle"></i></div>
                <div>
                    <p class="epin-action-title">Generate Pin</p>
                    <p class="epin-action-sub text-dark"> VISA wallet -- {{ showAmount(auth()->user()->visa) }}</p>
                </div>
            </div>
            <div class="epin-action-body">
                <div class="epin-amount-display">
                    <span class="epin-amount-label">Fixed Amount</span>
                    <span>
                        <span class="epin-amount-value">9,000</span>
                        <span class="epin-amount-cur">{{ gs('cur_text') }}</span>
                    </span>
                </div>
                <form action="{{ route('user.pin.generate') }}" method="POST">
                    @csrf
                    <input type="hidden" name="amount" value="9000">
                    <button type="submit" class="epin-btn green">
                        <i class="las la-qrcode"></i> Generate New Pin
                    </button>
                </form>
            </div>
        </div>

        {{-- How to use --}}
        <div class="epin-action-card">
            <div class="epin-action-header">
                <div class="epin-action-header-icon violet"><i class="las la-info-circle"></i></div>
                <div>
                    <p class="epin-action-title">How It Works</p>
                    <p class="epin-action-sub">Share & earn with E-Pins</p>
                </div>
            </div>
            <div class="epin-action-body">
                <div style="display:flex;flex-direction:column;gap:12px;">
                    <div style="display:flex;align-items:flex-start;gap:10px;">
                        <div style="width:28px;height:28px;border-radius:50%;background:#D1FAE5;color:#059669;display:flex;align-items:center;justify-content:center;font-size:.75rem;font-weight:800;flex-shrink:0;">1</div>
                        <div>
                            <p style="font-size:.8rem;font-weight:700;color:#111827;margin:0 0 2px;">Generate a Pin</p>
                            <p style="font-size:.72rem;color:#9CA3AF;margin:0;">9,000 {{ gs('cur_text') }} is deducted from your VISA wallet</p>
                        </div>
                    </div>
                    <div style="display:flex;align-items:flex-start;gap:10px;">
                        <div style="width:28px;height:28px;border-radius:50%;background:#EDE9FE;color:#7C3AED;display:flex;align-items:center;justify-content:center;font-size:.75rem;font-weight:800;flex-shrink:0;">2</div>
                        <div>
                            <p style="font-size:.8rem;font-weight:700;color:#111827;margin:0 0 2px;">Share the Pin</p>
                            <p style="font-size:.72rem;color:#9CA3AF;margin:0;">Copy and send the pin code to another member</p>
                        </div>
                    </div>
                    <div style="display:flex;align-items:flex-start;gap:10px;">
                        <div style="width:28px;height:28px;border-radius:50%;background:#FEF3C7;color:#D97706;display:flex;align-items:center;justify-content:center;font-size:.75rem;font-weight:800;flex-shrink:0;">3</div>
                        <div>
                            <p style="font-size:.8rem;font-weight:700;color:#111827;margin:0 0 2px;">Member activate new Account with this Pin </p>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    {{-- ── Pin List ── --}}
    <div class="epin-list-card">
        <div class="epin-list-head">
            <h6 class="epin-list-title">
                <i class="las la-list-alt"></i> My Generated Pins
            </h6>
        </div>

        {{-- Filter --}}
        <form method="GET">
            <div class="epin-filter">
                <input type="search" name="search" placeholder="Search pin..." value="{{ request('search') }}">
                <select name="status">
                    <option value="">All Status</option>
                    <option value="0" @selected(request('status') === '0')>Unused</option>
                    <option value="1" @selected(request('status') === '1')>Used</option>
                </select>
                <button type="submit" class="epin-filter-btn">
                    <i class="las la-filter"></i> Filter
                </button>
            </div>
        </form>

        @forelse($pins as $pin)
        <div class="epin-pin-row">
            <div class="epin-status-dot {{ $pin->status == 0 ? 'unused' : 'used' }}"></div>
            <div style="flex:1; min-width:0;">
                <div class="epin-pin-code" id="pin_{{ $loop->iteration }}">{{ $pin->pin }}</div>
                <div class="epin-pin-meta">
                    {{ showDateTime($pin->created_at, 'd M Y') }}
                    @if($pin->status == 1)
                        &bull; Used {{ diffForHumans($pin->updated_at) }}
                        &nbsp; &nbsp;
                        User By: {{ $pin->user->username }}
                    @endif

                </div>
            </div>
            <div class="epin-pin-right">
                <span class="epin-amount-chip">{{ getAmount($pin->amount) }} {{ gs('cur_text') }}</span>
                <span class="epin-badge {{ $pin->status == 0 ? 'unused' : 'used' }}">
                    {{ $pin->status == 0 ? 'Unused' : 'Used' }}
                </span>
                @if($pin->status == 0)
                <button class="epin-copy-btn" onclick="copyPin('pin_{{ $loop->iteration }}', this)" title="Copy Pin">
                    <i class="las la-copy"></i>
                </button>
                @endif
            </div>
        </div>
        @empty
        <div class="epin-empty">
            <div class="epin-empty-icon"><i class="las la-qrcode"></i></div>
            <h6>No pins generated yet</h6>
            <p>Click "Generate New Pin" above to create your first E-Pin.</p>
        </div>
        @endforelse
    </div>

    {{-- Pagination --}}
    @if($pins->hasPages())
        <div>{{ paginateLinks($pins) }}</div>
    @endif

</div>
@endsection

@push('script')
<script>
'use strict';
function copyPin(id, btn) {
    var text = document.getElementById(id).textContent.trim();
    try { navigator.clipboard.writeText(text); } catch(e) {
        var el = document.createElement('textarea');
        el.value = text; document.body.appendChild(el);
        el.select(); document.execCommand('copy');
        document.body.removeChild(el);
    }
    var icon = btn.querySelector('i');
    btn.classList.add('done');
    icon.className = 'las la-check';
    notify('success', 'Pin copied!');
    setTimeout(function(){ btn.classList.remove('done'); icon.className = 'las la-copy'; }, 2000);
}
</script>
@endpush
